daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
  - security
  - enhancement
staleLabel: wontfix
markComment: >
  This issue/pull request has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs in the next 7 days to
  keep our backlog clean. Thanks for your contributions.
closeComment: false