name: Check scripts executable 

on:
  push:
    branches: [ master ]

jobs:
  checkScriptsExecutable:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check and adjust scripts
      run: |
        ./Tools/check-scripts-executable.sh
    
    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
