name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches: [visualize_patch]
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.3.0
        with:
          excluded_paths: "ignore,.github,toolkit"
